Get-AppxPackage -allusers *3dbuilder* | Remove-AppxPackage
Get-AppxPackage -allusers *windowsalarms* | Remove-AppxPackage
Get-AppxPackage -allusers *windowscommunicationsapps* | Remove-AppxPackage
Get-AppxPackage -allusers *windowscamera* | Remove-AppxPackage
Get-AppxPackage -allusers *officehub* | Remove-AppxPackage
Get-AppxPackage -allusers *skypeapp* | Remove-AppxPackage
Get-AppxPackage -allusers *getstarted* | Remove-AppxPackage
Get-AppxPackage -allusers *zunemusic* | Remove-AppxPackage
Get-AppxPackage -allusers *windowsmaps* | Remove-AppxPackage
Get-AppxPackage -allusers *solitairecollection* | Remove-AppxPackage
Get-AppxPackage -allusers *bingfinance* | Remove-AppxPackage
Get-AppxPackage -allusers *zune* | Remove-AppxPackage
Get-AppxPackage -allusers *bingnews* | Remove-AppxPackage
Get-AppxPackage -allusers *onenote* | Remove-AppxPackage
Get-AppxPackage -allusers *people* | Remove-AppxPackage
Get-AppxPackage -allusers *windowsphone* | Remove-AppxPackage
Get-AppxPackage -allusers *windowsstore* | Remove-AppxPackage
Get-AppxPackage -allusers *bingsports* | Remove-AppxPackage
Get-AppxPackage -allusers *BingWeather* | Remove-AppxPackage
Get-AppxPackage -allusers *Xbox* | Remove-AppxPackage
Get-AppxPackage -allusers *duolingo* | Remove-AppxPackage
Get-AppxPackage -allusers *flipboard* | Remove-AppxPackage
Get-AppxPackage -allusers *NetworkSpeedTest* | Remove-AppxPackage
Get-AppxPackage -allusers *Advertising* | Remove-AppxPackage
Get-AppxPackage -allusers *WindowsFeedbackHub* | Remove-AppxPackage
Get-AppxPackage -allusers *OneConnect* | Remove-AppxPackage
Get-AppxPackage -allusers *Wunderlist* | Remove-AppxPackage
Get-AppxPackage -allusers *StorePurchaseApp* | Remove-AppxPackage
Get-AppxPackage -allusers *DesktopAppInstaller* | Remove-AppxPackage
Get-AppxPackage -allusers *FreshPaint* | Remove-AppxPackage
Get-AppxPackage -allusers *BingTranslator* | Remove-AppxPackage
Get-AppxPackage -allusers *ContactSupport* | Remove-AppxPackage
Get-AppxPackage -allusers *Sway* | Remove-AppxPackage